name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  swiftformat:
    name: Lint
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          brew install swiftformat
      - name: Lint
        run: |
          swiftformat --lint .
